### ISSUE TITLE
minor comment upon systime( ) 

### ISSUE THREAD

**Issue by mogando668** [p-j-miller/wmawk2#1]
Hi, first I'd like to say - great effort. for me, thee regular mawk2 is a godsend already.

just a minor point regarding your statement -- 

`The systime function was also added as this useful and is now common in other awk implementations and this function cannot be implemented as an awk script.`

I have to respectfully disagree with this statement. It is indeed possible to implement in script, using built-in functions, of standard awk variants without custom-compile or having to go  to POSIX sh to obtain it  —>

$ date | macos-built-in-awk '{ print srand(),srand() }'
1 1628641622
$ date | gawk '{ print srand(),srand() }'
1 1628641626
$ date | mawk '{ print srand(),srand() }'
1628641630 1628641630
$ date | mawk2 '{ print srand(),srand() }'
#srand1628641632.253287# #srand1628641632.254202#

In gnu-gawk and macos-built in one (i'm *guessing* it's a nawk-variant ?), the random seed defaults to 1, while mawk 1.3.4 and mawk2 defaults to epoch seconds already. upon 2nd call of srand( ) with no arguments, all variants will give you epoch seconds. in fact, mawk2 gives you at the micro-second level, far better than gawk (it's an undocumented feature, i merely accidentally stumbled upon it)

As long as one is comfortable with the implications that writing a generic function for all these 4 variants mean having to deal with a new-random seed (and i'm not aware of anywhere within awk user-space that can extract out info regarding how far along the LCG cycle for all calls to rand( ) prior to this srand( ) call, it would be nearly impossible to perfectly continue from the same spots. 

the way i do it myself

`function getEpochs(s6,e2) { 
      s6=srand();
      e2=srand(); 
      initRandSeed();                   # any function of your choice to handle re-setting of seed
      gsub(/[^0-9.]+/,"",e2); return e2+0 };
`

In fact, it's this unique-ness of mawk2 providing micro-second precision on epochs that my generic library identifies which variant of awk it's operating upon, and adjust its behavior regarding unicode-strings according

Nonetheless, I really appreciate your ya-printf( ) efforts. If you want a quick module to do ORD( ) CHR( ) LENGTH( ) and SUBSTR( ) on a unicode-safe-level using mawk2, lemme know i'll send you (they're just script-level functions).

MAWK2 is so insane that despite those being script-level functions not compiled C-binary code, it's quite competitive against both gawk, python, and even gnu-wc compiled-C-binary when it comes to counting characters in a file.

**Comment by p-j-miller** [comment]
Hi,
Thanks for your comments.
Checking the code srand() does indeed return a string thats based on the time, the line in bi_funct.c is:

    sprintf(buffer, "#srand%ld.%ld#", (long) tv.tv_sec, (long) tv.tv_usec);

However, that means if for example usec is 1 and sec is 1000 it will return #srand1000.1# which is not the correct time (which would be 1000.000001 ).  Knowing the implementation, it would in theory be possible to extract the time to microsecond resolution, but the code you provided in your comment above does not do that. 

I believe the current documentation is acceptable as it does not seem wise to encourage people to try and use srand for this, especially as systime() is now widely available in awk implementations. 
The current statement in the wmawk2 manual is:

    srand(expr) : Seeds the random number generator, using the clock if expr is omitted, and returns the  value of the previous seed.
    Wmawk2 seeds the random number generator from the clock at startup so there is no real need to call srand(). 
    Srand(expr) is useful for repeating pseudo  random sequences.

**Comment by mogando668** [comment]
I concur. I wasn’t remotely suggesting the method is proper , or fool proof , or even accurate, just a stupid back door solution for myself hahah. 

mawk2 is insanely fast. At a certain point I stopped bothering with loading reference tables in line by line - using both my usual field sep and \n, I tell mawk2 to throw the entire file flat on $0, and it can finish splitting and give me 7 or even 8 figure field numbers ( like $27463831 ) without breaking a sweat at all…  7 figure field count within 2.5 seconds, and maybe 8 seconds for 8 figure. Only past 100million field number before the loading time is above 25 seconds, but rarely above 1 minute 


Regards,
Jason K

**Comment by sergeevabc** [comment]
``` console
$ wmawk2.exe "BEGIN { today=strftime(\"%Y-%m-%d\");  print today; }"
line 2: function strftime never defined
```

Sorry, but can `systime` serve as a replacement for `strftime` here?

**Comment by p-j-miller** [comment]
I believe the strftime() function is a gnu awk extension so its only available as a built in function in gawk.

However, if you look at [AWK_library](https://github.com/p-j-miller/AWK_library/tree/main) file - strftime.awk you will find an awk function which will do what you require and should run in any version of awk.

 A simple example would be:

> test.awk:
  BEGIN{
	t=systime() # get time now (as a number in seconds)
	st=strftime_awk(t) # convert time into a string yyyy-mm-dd HH:MM:SS
	print " date/time now is:",st
      }

to run the above you would need to execute:

>  wmawk2 -f strftime.awk -f test.awk

If you wished to change the format of what is printed then you will either need to edit the last line of the strftime_awk function or use awk's string processing to change the returned string into the format you require - the function mktime_awk() in the same library shows how to do this using split.

This is mentioned on page 13 of the latest wmawk2 users guide.
